root: true
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    jsx: true
    experimentalObjectRestSpread: true
    globalReturn: true
env:
  node: true
  es6: true
  commonjs: true
  mocha: true
rules: {}
settings: {}
