root: true
parserOptions:
  ecmaVersion: 8
  sourceType: script
  ecmaFeatures:
    impliedStrict: false
    jsx: true
    experimentalObjectRestSpread: true
    globalReturn: true
env:
  node: true
  es6: true
  commonjs: true
  mocha: true
plugins:
- compat
- eslint-comments
- filenames
- fp
- html
- import
- markdown
- node
- promise
- unicorn
- you-dont-need-lodash-underscore
rules:
  # # Comments
  # no-inline-comments: 2
  # line-comment-position: 2
  # lines-around-comment: 2
  # spaced-comment: 2
  # capitalized-comments:
  # - 2
  # - always
  # - ignoreConsecutiveComments: true
  # # ESLint comments
  # eslint-comments/disable-enable-pair: 2
  # eslint-comments/no-unused-enable: 2
  # eslint-comments/no-duplicate-disable: 2
  # eslint-comments/no-unused-disable: 2
  # eslint-comments/no-unlimited-disable: 2
  # eslint-comments/no-use:
  # - 2
  # - allow:
  #   - 'eslint-disable'
  #   - 'eslint-enable'
  #   - 'eslint-disable-next-line'
  # # JSDoc
  # #  valid-jsdoc: 2
  # #  require-jsdoc:
  # #  - 2
  # #  - require:
  # #      FunctionDeclaration: true
  # #      MethodDefinition: true
  # #      ClassDeclaration: true
  # strict: 2
  # # Long statements
  # operator-linebreak: 2
  # newline-per-chained-call: 2
  # dot-location:
  # - 2
  # - property
  # no-whitespace-before-property: 2
  # # Blank lines
  # no-multiple-empty-lines:
  # - 2
  # - max: 2
  #   maxBOF: 0
  #   maxEOF: 0
  # padding-line-between-statements:
  # - 2
  # - blankLine: always
  #   prev: [multiline-block-like, directive]
  #   next: '*'
  # - blankLine: always
  #   prev: '*'
  #   next: multiline-block-like
  # padded-blocks:
  # - 2
  # - blocks: never
  #   classes: always
  #   switches: always
  # # Indentation
  # indent:
  # - 2
  # - 2
  # - SwitchCase: 1
  #   outerIIFEBody: 0
  # no-tabs: 2
  # no-mixed-spaces-and-tabs: 2
  # # Whitespaces
  # no-trailing-spaces: 2
  # no-multi-spaces: 2
  # no-irregular-whitespace: 2
  # linebreak-style: 2
  # eol-last: 2
  # unicode-bom: 2
  # # Braces
  # curly: 2
  # brace-style:
  # - 2
  # - 1tbs
  # - allowSingleLine: true
  # nonblock-statement-body-position: 2
  # # Spaces
  # block-spacing: 2
  # object-curly-spacing:
  # - 2
  # - always
  # space-before-blocks: 2
  # array-bracket-spacing: 2
  # computed-property-spacing: 2
  # space-in-parens: 2
  # template-tag-spacing: 2
  # template-curly-spacing: 2
  # comma-spacing: 2
  # semi-spacing: 2
  # key-spacing: 2
  # switch-colon-spacing: 2
  # space-unary-ops: 2
  # keyword-spacing: 2
  # space-infix-ops: 2
  # rest-spread-spacing: 2
  # func-call-spacing: 2
  # space-before-function-paren:
  # - 2
  # - anonymous: always
  #   named: never
  #   asyncArrow: always
  # arrow-spacing: 2
  # generator-star-spacing: 2
  # yield-star-spacing: 2
  # # Semicolons
  # semi: 2
  # semi-style: 2
  # no-unexpected-multiline: 2
  # no-extra-semi: 2
  # # Statements
  # no-empty: 2
  # no-unused-expressions: 2
  # no-new: 2
  # no-unreachable: 2
  # # Parenthesis
  # no-extra-parens:
  # - 2
  # - all
  # - nestedBinaryExpressions: false
  #   ignoreJSX: all
  # no-mixed-operators: 2
  # wrap-iife: 2
  # # Complexity
  # max-len:
  # - 2
  # - code: 80
  #   tabWidth: 2
  #   ignoreUrls: true
  #   ignoreStrings: true
  #   ignoreTemplateLiterals: true
  #   ignoreRegExpLiterals: true
  # max-lines:
  # - 2
  # - max: 100
  #   skipBlankLines: true
  #   skipComments: true
  # max-statements:
  # - 2
  # - 13
  # max-statements-per-line:
  # - 2
  # - max: 2
  # import/max-dependencies: 2
  # complexity:
  # - 2
  # - 5
  # max-depth:
  # - 2
  # - 2
  # max-nested-callbacks:
  # - 2
  # - 2
  # # Referencing
  # no-undef: 2
  # no-undef-init: 2
  # no-unused-vars: 2
  # no-redeclare:
  # - 2
  # - builtinGlobals: true
  # no-shadow:
  # - 2
  # - builtinGlobals: true
  #   hoist: all
  # no-shadow-restricted-names: 2
  # no-use-before-define:
  # - 2
  # - functions: true
  #   classes: false
  #   variables: false
  # # Declarations
  # block-scoped-var: 2
  # no-const-assign: 2
  # no-var: 2
  # fp/no-let: 2
  # import/no-mutable-exports: 2
  # prefer-const: 2
  # no-global-assign: 2
  # no-implicit-globals: 2
  # one-var:
  # - 2
  # - never
  # one-var-declaration-per-line: 2
  # vars-on-top: 2
  # no-inner-declarations: 2
  # sort-vars: 2
  # # fp/no-nil: 2
  # # Assignments
  # init-declarations: 2
  # no-plusplus: 2
  # operator-assignment: 2
  # no-multi-assign: 2
  # no-cond-assign: 2
  # no-return-assign: 2
  # no-self-assign: 2
  # no-param-reassign:
  # - 2
  # # - props: true
  # # fp/no-mutation:
  # # - 2
  # # - commonjs: true
  # # fp/no-unused-expression:
  # # - 2
  # # - allowUseStrict: true
  # import/no-unassigned-import: 2
  # # fp/no-mutating-assign: 2
  # # fp/no-mutating-methods: 2
  # # Naming
  # id-length:
  # - 2
  # - max: 25
  #   exceptions:
  #   - $
  #   - _
  # camelcase: 2
  # id-match:
  # - 2
  # - '^[A-Za-z0-9_]+$'
  # - onlyDeclarations: true
  # no-underscore-dangle: 2
  # new-cap: 2
  # # Typecasting
  # no-extra-boolean-cast: 2
  # no-implicit-coercion: 2
  # unicorn/explicit-length-check: 2
  # no-new-wrappers: 2
  # fp/no-valueof-field: 2
  # # Tests
  # no-unsafe-negation: 2
  # eqeqeq:
  # - 2
  # - smart
  # valid-typeof: 2
  # unicorn/no-array-instanceof: 2
  # no-negated-condition: 2
  # no-constant-condition: 2
  # no-self-compare: 2
  # yoda: 2
  # no-nested-ternary: 2
  # no-unneeded-ternary: 2
  # # Structures
  # no-lone-blocks: 2
  # no-lonely-if: 2
  # no-else-return: 2
  # no-unmodified-loop-condition: 2
  # for-direction: 2
  # guard-for-in: 2
  # # fp/no-loops: 2
  # # Switch
  # no-duplicate-case: 2
  # default-case: 2
  # no-fallthrough: 2
  # no-case-declarations: 2
  # # Labels
  # no-labels: 2
  # no-unused-labels: 2
  # no-extra-label: 2
  # no-label-var: 2
  # # Exceptions
  # no-throw-literal: 2
  # unicorn/throw-new-error: 2
  # unicorn/catch-error-name:
  # - 2
  # - name: innererror
  # no-ex-assign: 2
  # no-catch-shadow: 2
  # no-unsafe-finally: 2
  # no-debugger: 2
  # # fp/no-throw: 2
  # unicorn/custom-error-definition: 2
  # # Functions
  # func-style: 2
  # no-func-assign: 2
  # no-loop-func: 2
  # func-names:
  # - 2
  # - as-needed
  # func-name-matching: 2
  # prefer-arrow-callback: 2
  # arrow-body-style: 2
  # arrow-parens:
  # - 2
  # - as-needed
  # no-confusing-arrow: 2
  # max-params:
  # - 2
  # - 2
  # no-dupe-args: 2
  # prefer-spread: 2
  # prefer-rest-params: 2
  # fp/no-arguments: 2
  # require-yield: 2
  # accessor-pairs: 2
  # fp/no-get-set: 2
  # fp/no-proxy: 2
  # no-empty-function: 2
  # no-useless-return: 2
  # # Objects
  # object-property-newline:
  # - 2
  # - allowMultiplePropertiesPerLine: true
  # comma-style: 2
  # no-dupe-keys: 2
  # dot-notation: 2
  # no-useless-computed-key: 2
  # quote-props:
  # - 2
  # - as-needed
  # object-shorthand: 2
  # no-useless-rename: 2
  # prefer-destructuring:
  # - 2
  # - {}
  # - enforceForRenamedProperties: true
  # no-empty-pattern: 2
  # no-new-object: 2
  # # Inheritance
  # no-useless-constructor: 2
  # constructor-super: 2
  # no-this-before-super: 2
  # new-parens: 2
  # no-useless-call: 2
  # no-extra-bind: 2
  # class-methods-use-this: 2
  # consistent-this: 2
  # no-class-assign: 2
  # no-dupe-class-members: 2
  # no-proto: 2
  # no-prototype-builtins: 2
  # no-extend-native: 2
  # # fp/no-class: 2
  # # Arrays
  # comma-dangle:
  # - 2
  # - always-multiline
  # no-sparse-arrays: 2
  # array-callback-return: 2
  # no-array-constructor: 2
  # # String
  # quotes:
  # - 2
  # - single
  # no-multi-str: 2
  # no-useless-concat: 2
  # prefer-template: 2
  # no-template-curly-in-string: 2
  # unicorn/prefer-starts-ends-with: 2
  # unicorn/no-hex-escape: 2
  # unicorn/number-literal-case: 2
  # unicorn/escape-case: 2
  # # RegExps
  # no-useless-escape: 2
  # no-control-regex: 2
  # no-div-regex: 2
  # no-empty-character-class: 2
  # no-regex-spaces: 2
  # no-invalid-regexp: 2
  # wrap-regex: 2
settings: {}
