models:
  pet:
    type: object
    description: Cute animal
    required: [id, name, photo_urls, friends]
    operations: [find, create, replace, update, upsert, deleteOne, deleteMany]
    properties:
      id:
        type: string
        description: Unique identifier of a pet
      name:
        type: string
        examples: [doggie]
        description: How to call a pet
        default: default does not work if required
      weight:
        type: number
        description: Corrolated to how much a pet has eaten
        deprecated: Let's stop measuring pet's weight
        default: 15
      is_overweight:
        type: boolean
        description: Has the pet being eating too much?
        default: false
      photo_urls:
        type: array
        description: Sweet pictures of a pet
        items:
          type: string
      attributes:
        type: object
        description: Attributes of a pet
        properties:
          age:
            type: integer
            description: How old is the pet
            default: 1
          intelligence:
            type: integer
            description: How smart is the pet
        default: {}
      tags:
        type: array
        description: Tags applying to this pet
        items:
          type: string
        default: []
      status:
        type: string
        description: Has this pet been adopted
        default: adopted
      best_friend:
        instanceof: pet
        description: This pet's best friend
      friends:
        type: array
        description: This pet's friends
        items:
          instanceof: pet
operations: [find, create, replace, update, upsert, deleteOne, deleteMany]
